INSERT INTO PUBLIC."common" ("type", "value", "text", "description", "sequence", "parent_id") VALUES
	('Account', 'ACC01', 'Cash', NULL, 1, NULL),
	('Account', 'ACC02', 'Bank Account', NULL, 2, NULL),
	('Account', 'ACC03', 'ATM', NULL, 3, NULL),
	('Account', 'ACC04', 'Deposit Account', NULL, 4, NULL),
	('Account', 'ACC05', 'Save Account', NULL, 5, NULL),
	('Account', 'ACC06', 'Other', NULL, 6, NULL),

	('Expense', 'EXP01', 'Lend', NULL, 1, NULL),
	('Expense', 'EXP02', 'Repayment', NULL, 2, NULL),
	('Expense', 'EXP03', 'Food And Dining', NULL, 3, NULL),
	('Expense', 'EXP04', 'Utilities', NULL, 4, NULL),
	('Expense', 'EXP05', 'Auto & Transport', NULL, 5, NULL),
	('Expense', 'EXP06', 'Kids', NULL, 6, NULL),
	('Expense', 'EXP07', 'Clothing', NULL, 7, NULL),
	('Expense', 'EXP08', 'Gift & Donations', NULL, 8, NULL),
	('Expense', 'EXP09', 'Health & Fitness', NULL, 9, NULL),
	('Expense', 'EXP10', 'Home', NULL, 10, NULL),
	('Expense', 'EXP11', 'Entertainment', NULL, 11, NULL),
	('Expense', 'EXP12', 'Personal', NULL, 12, NULL),
	('Expense', 'EXP13', 'Groceries', NULL, 13, 9),
	('Expense', 'EXP14', 'Restaurant', NULL, 14, 9),
	('Expense', 'EXP15', 'Bars & Coffee', NULL, 15, 9),
	('Expense', 'EXP16', 'Water', NULL, 16, 10),
	('Expense', 'EXP17', 'Electricity', NULL, 17, 10),
	('Expense', 'EXP18', 'Internet', NULL, 18, 10),
	('Expense', 'EXP19', 'Gas', NULL, 19, 10),
	('Expense', 'EXP20', 'Cable TV', NULL, 20, 10),
	('Expense', 'EXP21', 'Mobile Phone', NULL, 21, 10),
	('Expense', 'EXP22', 'Home Phone', NULL, 22, 10),
	('Expense', 'EXP23', 'Hiring Maid', NULL, 23, 10),
	('Expense', 'EXP24', 'Fuel', NULL, 24, 11),
	('Expense', 'EXP25', 'Service & Parts', NULL, 25, 11),
	('Expense', 'EXP26', 'Repair Vehicles', NULL, 26, 11),
	('Expense', 'EXP27', 'Parking', NULL, 27, 11),
	('Expense', 'EXP28', 'Car Wash', NULL, 28, 11),
	('Expense', 'EXP29', 'Taxi', NULL, 29, 11),
	('Expense', 'EXP30', 'Tuition', NULL, 30, 12),
	('Expense', 'EXP31', 'Books', NULL, 31, 12),
	('Expense', 'EXP32', 'Baby Supplies', NULL, 32, 12),
	('Expense', 'EXP33', 'Toys', NULL, 33, 12),
	('Expense', 'EXP34', 'Allowance', NULL, 34, 12),
	('Expense', 'EXP35', 'Clothes', NULL, 35, 13),
	('Expense', 'EXP36', 'Shoes', NULL, 36, 13),
	('Expense', 'EXP37', 'Accessories', NULL, 37, 13),
	('Expense', 'EXP38', 'Marriages', NULL, 38, 14),
	('Expense', 'EXP39', 'Funerals', NULL, 39, 14),
	('Expense', 'EXP40', 'Charity', NULL, 40, 14),
	('Expense', 'EXP41', 'Gifts', NULL, 41, 14),
	('Expense', 'EXP42', 'Doctor', NULL, 42, 15),
	('Expense', 'EXP43', 'Pharmacy', NULL, 43, 15),
	('Expense', 'EXP44', 'Sports', NULL, 44, 15),
	('Expense', 'EXP45', 'Furnishing', NULL, 45, 16),
	('Expense', 'EXP46', 'Repair Of Buildings', NULL, 46, 16),
	('Expense', 'EXP47', 'Home Services', NULL, 47, 16),
	('Expense', 'EXP48', 'Music', NULL, 48, 17),
	('Expense', 'EXP49', 'Travel', NULL, 49, 17),
	('Expense', 'EXP50', 'Make Up', NULL, 50, 17),
	('Expense', 'EXP51', 'Movies & DVDs', NULL, 51, 17),
	('Expense', 'EXP52', 'Cosmetic', NULL, 52, 17),	
	('Expense', 'EXP53', 'Education', NULL, 53, 18),
	('Expense', 'EXP54', 'Hobbies', NULL, 54, 18),

	('Income', 'INC01', 'Borrow', NULL, 1, NULL),
	('Income', 'INC02', 'Collecting Debts', NULL, 2, NULL),
	('Income', 'INC03', 'Salary', NULL, 3, NULL),	
	('Income', 'INC04', 'Bonus', NULL, 4, NULL),
	('Income', 'INC05', 'Awarded', NULL, 6, NULL),
	('Income', 'INC06', 'Interest', NULL, 7, NULL),
	('Income', 'INC07', 'Savings Interest', NULL, 6, NULL),

	('Setting', 'SET01', 'Reminder', NULL, 1, NULL),
	('Setting', 'SET02', 'Currency', NULL, 1, NULL),

	('Currency', 'VND', 'Việt Nam Đồng', NULL, 1, NULL),
	('Currency', 'USD', 'United States Dollar', NULL, 2, NULL),
	('Currency', 'EUR', 'Euro', NULL, 3, NULL),

	('Term', 'TRM01', '1 Week', NULL, 1, NULL),
	('Term', 'TRM02', '2 Weeks', NULL, 2, NULL),
	('Term', 'TRM03', '3 Weeks', NULL, 3, NULL),
	('Term', 'TRM04', '1 Month', NULL, 4, NULL),
	('Term', 'TRM05', '3 Months', NULL, 5, NULL),
	('Term', 'TRM06', '6 Months', NULL, 6, NULL),
	('Term', 'TRM07', '12 Months', NULL, 7, NULL),
	('Term', 'TRM08', 'Other', NULL, 8, NULL),

	('InterestPaid', 'IPD01', 'Up-front', NULL, 1, NULL),
	('InterestPaid', 'IPD02', 'Maturity', NULL, 2, NULL),
	('InterestPaid', 'IPD03', 'Monthly', NULL, 3, NULL),
	('InterestPaid', 'IPD04', 'Quarterly', NULL, 4, NULL),

	('TermEnd', 'TRE01', 'Rollover principal', NULL, 1, NULL),
	('TermEnd', 'TRE02', 'Rollover principal and interest', NULL, 2, NULL),
	('TermEnd', 'TRE03', 'Close account', NULL, 3, NULL);